import React, { useEffect, useState } from 'react';
import './App.css';
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, getDocs } from 'firebase/firestore';
import { getAuth, onAuthStateChanged } from 'firebase/auth';
import AuthForm from './AuthForm';
import UploadChapter from './UploadChapter';

// Firebase configuration
const firebaseConfig = {
  apiKey: process.env.REACT_APP_FIREBASE_API_KEY,
    authDomain: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
      projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID,
        storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
          messagingSenderId: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
            appId: process.env.REACT_APP_FIREBASE_APP_ID,
              measurementId: process.env.REACT_APP_FIREBASE_MEASUREMENT_ID,
              };

              const app = initializeApp(firebaseConfig);
              const db = getFirestore(app);

              function App() {
                const [novels, setNovels] = useState([]);
                  const [user, setUser] = useState(null); // State to track authenticated user
                    const [searchTerm, setSearchTerm] = useState(''); // For searching novels

                      // Fetch novels from Firestore
                        useEffect(() => {
                            const fetchNovels = async () => {
                                  const querySnapshot = await getDocs(collection(db, 'Novels'));
                                        const novelsList = querySnapshot.docs.map(doc => ({
                                                id: doc.id,
                                                        ...doc.data(),
                                                              }));
                                                                    setNovels(novelsList);
                                                                        };
                                                                            fetchNovels();
                                                                              }, []);

                                                                                useEffect(() => {
                                                                                    const auth = getAuth();
                                                                                        onAuthStateChanged(auth, (currentUser) => {
                                                                                              setUser(currentUser);
                                                                                                  });
                                                                                                    }, []);

                                                                                                      // Filter novels by title or author based on search term
                                                                                                        const filteredNovels = novels.filter(
                                                                                                            (novel) =>
                                                                                                                  novel.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                                                                                                                        novel.author.toLowerCase().includes(searchTerm.toLowerCase())
                                                                                                                          );

                                                                                                                            return (
                                                                                                                                <div>
                                                                                                                                      {user ? (
                                                                                                                                              <div>
                                                                                                                                                        {/* Display navigation and novels when authenticated */}
                                                                                                                                                                  <nav>
                                                                                                                                                                              <img
                                                                                                                                                                                            src="https://images.app.goo.gl/CP3wSZ5V3VVbC1ZYA"
                                                                                                                                                                                                          alt="Logo"
                                                                                                                                                                                                                        className="logo"
                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                <ul>
                                                                                                                                                                                                                                                              <li>Home</li>
                                                                                                                                                                                                                                                                            <li>Profile</li>
                                                                                                                                                                                                                                                                                          <li>Genres</li>
                                                                                                                                                                                                                                                                                                        <li>My Novels</li>
                                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                                                                                                            placeholder="Search novels..."
                                                                                                                                                                                                                                                                                                                                                                          value={searchTerm}
                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setSearchTerm(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                              </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Carousel for Genres */}
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="carousel">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                            src="https://images.app.goo.gl/YaFgac1tbx48vpVe9"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alt="Fantasy"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                src="https://images.app.goo.gl/PNFkqMVYA28Sj3QQ7"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alt="Horror"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    src="https://images.app.goo.gl/8RXi5jjRg1gXpxKFA"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alt="Mystery"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        src="https://images.app.goo.gl/sbo4Ar2WsEEwAaGb6"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      alt="Adventure"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            src="https://images.app.goo.gl/gRk3ocrzm7ozQeaL7"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alt="Romance"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                src="https://images.app.goo.gl/SQVMpLYhniWDkNNF9"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alt="Sci-Fi"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Display filtered novels */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2>Novels</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="novels-list">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {filteredNovels.map((novel) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={novel.id} className="novel-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {novel.NovelCoverpage ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src={novel.NovelCoverpage} alt={`${novel.title} Cover`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="default-cover">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>{novel.title}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>by {novel.author}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>{novel.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>{novel.author}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <UploadChapter novelId={novel.id} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <AuthForm setUser={setUser} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default App;